name: madpicker
description: A new Flutter package project.
version: 0.0.1
homepage: madstudio.dev

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter



flutter: null
